import { z } from 'zod';


const PathsSchema = z.object({
  auth: z.object({
    signIn: z.string().min(1),
    signUp: z.string().min(1),
    signUpAgencyMember: z.string().min(1),
    pendingApproval: z.string().min(1),
    verifyMfa: z.string().min(1),
    callback: z.string().min(1),
    passwordReset: z.string().min(1),
    passwordUpdate: z.string().min(1),
  }),
  app: z.object({
    home: z.string().min(1),
    dashboard: z.string().min(1),
    toolCopyList: z.string().min(1),
    catalogProvider: z.string().min(1),
    catalog: z.string().min(1),
    training: z.string().min(1),
    catalogProduct: z.string().min(1),
    catalogSourcingChina: z.string().min(1),
    partners: z.string().min(1),
    catalogWholesale: z.string().min(1),
    catalogPrivateLabel: z.string().min(1),
    messages: z.string().min(1),
    orders: z.string().min(1),
    calendar: z.string().min(1),
    users: z.string().min(1),
    services: z.string().min(1),
    servicesCatalog: z.string().min(1),
    invoices: z.string().min(1),
    personalAccountSettings: z.string().min(1),
    personalAccountBilling: z.string().min(1),
    personalAccountBillingReturn: z.string().min(1),
    accountHome: z.string().min(1),
    accountSettings: z.string().min(1),
    accountBilling: z.string().min(1),
    accountMembers: z.string().min(1),
    accountBillingReturn: z.string().min(1),
    joinTeam: z.string().min(1),
    team: z.string().min(1),
    clients: z.string().min(1),
    briefs: z.string().min(1),
    organization: z.string().min(1),
    storage: z.string().min(1),
    setPassword: z.string().min(1),
    apps: z.string().min(1),
    embeds: z.string().min(1),
  }),
});

const pathsConfig = PathsSchema.parse({
  auth: {
    signIn: '/auth/sign-in',
    signUp: '/auth/sign-up',
    signUpAgencyMember: '/auth/sign-up/member',
    pendingApproval: '/auth/pending-approval',
    verifyMfa: '/auth/verify',
    callback: '/auth/callback',
    passwordReset: '/auth/password-reset',
    passwordUpdate: '/update-password',
  },
  app: {
    home: '/home',
    dashboard: '/dashboard',
    team: '/team',
    clients: '/clients',
    orders: '/orders',
    messages: '/messages',
    users: '/users',
    toolCopyList: '/tools/copy-listing',
    training: '/training',
    catalogProvider: '/catalog/providers',
    catalog: '/catalog',
    catalogSourcingChina: '/catalog/sourcing-china',
    catalogProduct: '/catalog/products',
    catalogWholesale: '/catalog/products/wholesale',
    catalogPrivateLabel: '/catalog/products/private-label',
    partners: '/partners',
    services: '/services',
    servicesCatalog: '/services/catalog',
    invoices: '/invoices',
    personalAccountSettings: '/home/settings',
    personalAccountBilling: '/home/billing',
    // personalAccountBilling: '/billing',
    personalAccountBillingReturn: '/home/billing/return',
    accountHome: '/home/[account]',
    accountSettings: `/home/[account]/settings`,
    accountBilling: `/home/[account]/billing`,
    accountMembers: `/home/[account]/members`,
    accountBillingReturn: `/home/[account]/billing/return`,
    joinTeam: '/join',
    organization: '/organization',
    storage: '/storage',
    briefs: '/briefs',
    setPassword: '/set-password',
    apps: '/apps',
    embeds: '/embeds',
    calendar: '/calendar',
  },
} satisfies z.infer<typeof PathsSchema>);

export default pathsConfig;