create type "public"."action_type" as enum ('create', 'update', 'delete');

create type "public"."activity_type" as enum ('message', 'review', 'status', 'priority', 'assign', 'due_date', 'description');

create type "public"."order_status_types" as enum ('in_progress', 'in_review', 'pending', 'completed', 'annulled');

create type "public"."priority_types" as enum ('high', 'medium', 'low');

create type "public"."reaction_types" as enum ('like', 'favorite');

create table "public"."activities" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "type" action_type not null,
    "action" action_type not null,
    "message" text not null,
    "user_id" uuid not null default gen_random_uuid()
);


alter table "public"."activities" enable row level security;

create table "public"."messages" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "content" text default ''::text,
    "updated_at" timestamp without time zone not null default now()
);


alter table "public"."messages" enable row level security;

create table "public"."reactions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "emoji" text not null,
    "user_id" uuid not null,
    "type" reaction_types not null
);


alter table "public"."reactions" enable row level security;

create table "public"."reviews" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "content" text not null,
    "rating" numeric not null default '0'::numeric,
    "updated_at" timestamp without time zone not null default now(),
    "user_id" uuid not null default gen_random_uuid()
);


alter table "public"."reviews" enable row level security;

alter table "public"."files" add column "message_id" uuid;

alter table "public"."orders_v2" add column "priority" priority_types default 'low'::priority_types;

alter table "public"."orders_v2" alter column "propietary_organization_id" set not null;

alter table "public"."orders_v2" alter column "status" set default 'pending'::order_status_types;

alter table "public"."orders_v2" alter column "status" set data type order_status_types using "status"::order_status_types;

CREATE UNIQUE INDEX activities_pkey ON public.activities USING btree (id);

CREATE UNIQUE INDEX message_pkey ON public.messages USING btree (id);

CREATE UNIQUE INDEX reactions_pkey ON public.reactions USING btree (id);

CREATE UNIQUE INDEX reviews_pkey ON public.reviews USING btree (id);

alter table "public"."activities" add constraint "activities_pkey" PRIMARY KEY using index "activities_pkey";

alter table "public"."messages" add constraint "message_pkey" PRIMARY KEY using index "message_pkey";

alter table "public"."reactions" add constraint "reactions_pkey" PRIMARY KEY using index "reactions_pkey";

alter table "public"."reviews" add constraint "reviews_pkey" PRIMARY KEY using index "reviews_pkey";

alter table "public"."activities" add constraint "activities_user_id_fkey" FOREIGN KEY (user_id) REFERENCES accounts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."activities" validate constraint "activities_user_id_fkey";

alter table "public"."files" add constraint "files_message_id_fkey" FOREIGN KEY (message_id) REFERENCES messages(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."files" validate constraint "files_message_id_fkey";

alter table "public"."reactions" add constraint "reactions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES accounts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."reactions" validate constraint "reactions_user_id_fkey";

alter table "public"."reviews" add constraint "reviews_user_id_fkey" FOREIGN KEY (user_id) REFERENCES accounts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."reviews" validate constraint "reviews_user_id_fkey";

grant delete on table "public"."activities" to "anon";

grant insert on table "public"."activities" to "anon";

grant references on table "public"."activities" to "anon";

grant select on table "public"."activities" to "anon";

grant trigger on table "public"."activities" to "anon";

grant truncate on table "public"."activities" to "anon";

grant update on table "public"."activities" to "anon";

grant delete on table "public"."activities" to "authenticated";

grant insert on table "public"."activities" to "authenticated";

grant references on table "public"."activities" to "authenticated";

grant select on table "public"."activities" to "authenticated";

grant trigger on table "public"."activities" to "authenticated";

grant truncate on table "public"."activities" to "authenticated";

grant update on table "public"."activities" to "authenticated";

grant delete on table "public"."activities" to "service_role";

grant insert on table "public"."activities" to "service_role";

grant references on table "public"."activities" to "service_role";

grant select on table "public"."activities" to "service_role";

grant trigger on table "public"."activities" to "service_role";

grant truncate on table "public"."activities" to "service_role";

grant update on table "public"."activities" to "service_role";

grant delete on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "anon";

grant references on table "public"."messages" to "anon";

grant select on table "public"."messages" to "anon";

grant trigger on table "public"."messages" to "anon";

grant truncate on table "public"."messages" to "anon";

grant update on table "public"."messages" to "anon";

grant delete on table "public"."messages" to "authenticated";

grant insert on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant trigger on table "public"."messages" to "authenticated";

grant truncate on table "public"."messages" to "authenticated";

grant update on table "public"."messages" to "authenticated";

grant delete on table "public"."messages" to "service_role";

grant insert on table "public"."messages" to "service_role";

grant references on table "public"."messages" to "service_role";

grant select on table "public"."messages" to "service_role";

grant trigger on table "public"."messages" to "service_role";

grant truncate on table "public"."messages" to "service_role";

grant update on table "public"."messages" to "service_role";

grant delete on table "public"."reactions" to "anon";

grant insert on table "public"."reactions" to "anon";

grant references on table "public"."reactions" to "anon";

grant select on table "public"."reactions" to "anon";

grant trigger on table "public"."reactions" to "anon";

grant truncate on table "public"."reactions" to "anon";

grant update on table "public"."reactions" to "anon";

grant delete on table "public"."reactions" to "authenticated";

grant insert on table "public"."reactions" to "authenticated";

grant references on table "public"."reactions" to "authenticated";

grant select on table "public"."reactions" to "authenticated";

grant trigger on table "public"."reactions" to "authenticated";

grant truncate on table "public"."reactions" to "authenticated";

grant update on table "public"."reactions" to "authenticated";

grant delete on table "public"."reactions" to "service_role";

grant insert on table "public"."reactions" to "service_role";

grant references on table "public"."reactions" to "service_role";

grant select on table "public"."reactions" to "service_role";

grant trigger on table "public"."reactions" to "service_role";

grant truncate on table "public"."reactions" to "service_role";

grant update on table "public"."reactions" to "service_role";

grant delete on table "public"."reviews" to "anon";

grant insert on table "public"."reviews" to "anon";

grant references on table "public"."reviews" to "anon";

grant select on table "public"."reviews" to "anon";

grant trigger on table "public"."reviews" to "anon";

grant truncate on table "public"."reviews" to "anon";

grant update on table "public"."reviews" to "anon";

grant delete on table "public"."reviews" to "authenticated";

grant insert on table "public"."reviews" to "authenticated";

grant references on table "public"."reviews" to "authenticated";

grant select on table "public"."reviews" to "authenticated";

grant trigger on table "public"."reviews" to "authenticated";

grant truncate on table "public"."reviews" to "authenticated";

grant update on table "public"."reviews" to "authenticated";

grant delete on table "public"."reviews" to "service_role";

grant insert on table "public"."reviews" to "service_role";

grant references on table "public"."reviews" to "service_role";

grant select on table "public"."reviews" to "service_role";

grant trigger on table "public"."reviews" to "service_role";

grant truncate on table "public"."reviews" to "service_role";

grant update on table "public"."reviews" to "service_role";

create policy "Create for all authenticated users"
on "public"."activities"
as permissive
for insert
to authenticated
with check (true);


create policy "Delete for all authenticated users"
on "public"."activities"
as permissive
for delete
to authenticated
using (true);


create policy "Read for all authenticated users"
on "public"."activities"
as permissive
for select
to authenticated
using (true);


create policy "Update for all authenticated users"
on "public"."activities"
as permissive
for insert
to authenticated
with check (true);


create policy "Create for all authenticated users"
on "public"."messages"
as permissive
for insert
to authenticated
with check (true);


create policy "Delete for all authenticated users"
on "public"."messages"
as permissive
for delete
to authenticated
using (true);


create policy "Read for all authenticated users"
on "public"."messages"
as permissive
for select
to authenticated
using (true);


create policy "Update for all authenticated users"
on "public"."messages"
as permissive
for update
to authenticated
using (true);


create policy "Create for all authenticated users"
on "public"."reactions"
as permissive
for insert
to authenticated
with check (true);


create policy "Delete for all authenticated users"
on "public"."reactions"
as permissive
for delete
to authenticated
using (true);


create policy "Read for all authenticated users"
on "public"."reactions"
as permissive
for select
to authenticated
using (true);


create policy "Update for all authenticated users"
on "public"."reactions"
as permissive
for update
to authenticated
using (true);


create policy "Create for all authenticated users"
on "public"."reviews"
as permissive
for insert
to authenticated
with check (true);


create policy "Delete for all authenticated users"
on "public"."reviews"
as permissive
for delete
to authenticated
using (true);


create policy "Read for all authenticated users"
on "public"."reviews"
as permissive
for select
to authenticated
using (true);


create policy "Update for all authenticated users"
on "public"."reviews"
as permissive
for update
to authenticated
using (true);





