create table "public"."orders_v2" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text,
    "description" text,
    "customer_id" text,
    "status" text,
    "assigned_to" text[],
    "due_date" date,
    "propietary_organization_id" text
);


alter table "public"."orders_v2" enable row level security;

CREATE UNIQUE INDEX orders_v2_pkey ON public.orders_v2 USING btree (id);

alter table "public"."orders_v2" add constraint "orders_v2_pkey" PRIMARY KEY using index "orders_v2_pkey";

grant delete on table "public"."orders_v2" to "anon";

grant insert on table "public"."orders_v2" to "anon";

grant references on table "public"."orders_v2" to "anon";

grant select on table "public"."orders_v2" to "anon";

grant trigger on table "public"."orders_v2" to "anon";

grant truncate on table "public"."orders_v2" to "anon";

grant update on table "public"."orders_v2" to "anon";

grant delete on table "public"."orders_v2" to "authenticated";

grant insert on table "public"."orders_v2" to "authenticated";

grant references on table "public"."orders_v2" to "authenticated";

grant select on table "public"."orders_v2" to "authenticated";

grant trigger on table "public"."orders_v2" to "authenticated";

grant truncate on table "public"."orders_v2" to "authenticated";

grant update on table "public"."orders_v2" to "authenticated";

grant delete on table "public"."orders_v2" to "service_role";

grant insert on table "public"."orders_v2" to "service_role";

grant references on table "public"."orders_v2" to "service_role";

grant select on table "public"."orders_v2" to "service_role";

grant trigger on table "public"."orders_v2" to "service_role";

grant truncate on table "public"."orders_v2" to "service_role";

grant update on table "public"."orders_v2" to "service_role";

create policy "orders_insert"
on "public"."orders_v2"
as permissive
for insert
to authenticated
with check (true);


create policy "orders_read"
on "public"."orders_v2"
as permissive
for select
to authenticated
using (true);


create policy "orders_update"
on "public"."orders_v2"
as permissive
for update
to authenticated
using (true)
with check (true);



