-- alter table "public"."files" alter column "type" set data type text using "type"::text;

-- alter table "public"."order_files" alter column "order_id" set data type uuid using "order_id"::uuid;

-- alter table "public"."orders_v2" add column "order_number" bigint generated by default as identity not null;

-- alter table "public"."orders_v2" alter column "id" drop identity;

-- alter table "public"."orders_v2" alter column "id" set data type uuid using "id"::uuid;


