create table "public"."agency_statuses" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "status_name" text,
    "status_color" text,
    "agency_id" uuid
);


alter table "public"."agency_statuses" enable row level security;

CREATE UNIQUE INDEX agency_statuses_pkey ON public.agency_statuses USING btree (id);

alter table "public"."agency_statuses" add constraint "agency_statuses_pkey" PRIMARY KEY using index "agency_statuses_pkey";

alter table "public"."agency_statuses" add constraint "agency_statuses_agency_id_fkey" FOREIGN KEY (agency_id) REFERENCES accounts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."agency_statuses" validate constraint "agency_statuses_agency_id_fkey";

grant delete on table "public"."agency_statuses" to "anon";

grant insert on table "public"."agency_statuses" to "anon";

grant references on table "public"."agency_statuses" to "anon";

grant select on table "public"."agency_statuses" to "anon";

grant trigger on table "public"."agency_statuses" to "anon";

grant truncate on table "public"."agency_statuses" to "anon";

grant update on table "public"."agency_statuses" to "anon";

grant delete on table "public"."agency_statuses" to "authenticated";

grant insert on table "public"."agency_statuses" to "authenticated";

grant references on table "public"."agency_statuses" to "authenticated";

grant select on table "public"."agency_statuses" to "authenticated";

grant trigger on table "public"."agency_statuses" to "authenticated";

grant truncate on table "public"."agency_statuses" to "authenticated";

grant update on table "public"."agency_statuses" to "authenticated";

grant delete on table "public"."agency_statuses" to "service_role";

grant insert on table "public"."agency_statuses" to "service_role";

grant references on table "public"."agency_statuses" to "service_role";

grant select on table "public"."agency_statuses" to "service_role";

grant trigger on table "public"."agency_statuses" to "service_role";

grant truncate on table "public"."agency_statuses" to "service_role";

grant update on table "public"."agency_statuses" to "service_role";

create policy "Delete for authenticated users"
on "public"."agency_statuses"
as permissive
for delete
to public
using (true);


create policy "Enable insert for authenticated users"
on "public"."agency_statuses"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable read access for authenticated users"
on "public"."agency_statuses"
as permissive
for select
to authenticated
using (true);


create policy "Update for authenticated users"
on "public"."agency_statuses"
as permissive
for update
to authenticated
using (true);


