create table "public"."briefs" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "propietary_organization_id" text
);


alter table "public"."briefs" enable row level security;

create table "public"."service_briefs" (
    "service_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "brief_id" uuid not null default gen_random_uuid()
);


alter table "public"."service_briefs" enable row level security;

CREATE UNIQUE INDEX briefs_pkey ON public.briefs USING btree (id);

CREATE UNIQUE INDEX service_briefs_pkey ON public.service_briefs USING btree (service_id, brief_id);

alter table "public"."briefs" add constraint "briefs_pkey" PRIMARY KEY using index "briefs_pkey";

alter table "public"."service_briefs" add constraint "service_briefs_pkey" PRIMARY KEY using index "service_briefs_pkey";

alter table "public"."service_briefs" add constraint "service_briefs_brief_id_fkey" FOREIGN KEY (brief_id) REFERENCES briefs(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."service_briefs" validate constraint "service_briefs_brief_id_fkey";

alter table "public"."service_briefs" add constraint "service_briefs_service_id_fkey" FOREIGN KEY (service_id) REFERENCES services(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."service_briefs" validate constraint "service_briefs_service_id_fkey";

grant delete on table "public"."briefs" to "anon";

grant insert on table "public"."briefs" to "anon";

grant references on table "public"."briefs" to "anon";

grant select on table "public"."briefs" to "anon";

grant trigger on table "public"."briefs" to "anon";

grant truncate on table "public"."briefs" to "anon";

grant update on table "public"."briefs" to "anon";

grant delete on table "public"."briefs" to "authenticated";

grant insert on table "public"."briefs" to "authenticated";

grant references on table "public"."briefs" to "authenticated";

grant select on table "public"."briefs" to "authenticated";

grant trigger on table "public"."briefs" to "authenticated";

grant truncate on table "public"."briefs" to "authenticated";

grant update on table "public"."briefs" to "authenticated";

grant delete on table "public"."briefs" to "service_role";

grant insert on table "public"."briefs" to "service_role";

grant references on table "public"."briefs" to "service_role";

grant select on table "public"."briefs" to "service_role";

grant trigger on table "public"."briefs" to "service_role";

grant truncate on table "public"."briefs" to "service_role";

grant update on table "public"."briefs" to "service_role";

grant delete on table "public"."service_briefs" to "anon";

grant insert on table "public"."service_briefs" to "anon";

grant references on table "public"."service_briefs" to "anon";

grant select on table "public"."service_briefs" to "anon";

grant trigger on table "public"."service_briefs" to "anon";

grant truncate on table "public"."service_briefs" to "anon";

grant update on table "public"."service_briefs" to "anon";

grant delete on table "public"."service_briefs" to "authenticated";

grant insert on table "public"."service_briefs" to "authenticated";

grant references on table "public"."service_briefs" to "authenticated";

grant select on table "public"."service_briefs" to "authenticated";

grant trigger on table "public"."service_briefs" to "authenticated";

grant truncate on table "public"."service_briefs" to "authenticated";

grant update on table "public"."service_briefs" to "authenticated";

grant delete on table "public"."service_briefs" to "service_role";

grant insert on table "public"."service_briefs" to "service_role";

grant references on table "public"."service_briefs" to "service_role";

grant select on table "public"."service_briefs" to "service_role";

grant trigger on table "public"."service_briefs" to "service_role";

grant truncate on table "public"."service_briefs" to "service_role";

grant update on table "public"."service_briefs" to "service_role";

create policy "Create brief"
on "public"."briefs"
as permissive
for insert
to authenticated
with check (true);


create policy "Delete brief"
on "public"."briefs"
as permissive
for delete
to authenticated
using (true);


create policy "Read briefs"
on "public"."briefs"
as permissive
for select
to authenticated
using (true);


create policy "Update brief"
on "public"."briefs"
as permissive
for update
to authenticated
using (true);


create policy "Add service brief"
on "public"."service_briefs"
as permissive
for insert
to authenticated
with check (true);


create policy "Delete service brief"
on "public"."service_briefs"
as permissive
for delete
to authenticated
using (true);


create policy "Read service brief"
on "public"."service_briefs"
as permissive
for select
to authenticated
using (true);


create policy "Update service brief"
on "public"."service_briefs"
as permissive
for update
to authenticated
using (true);




