create table "public"."client_services" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "created_by" uuid not null,
    "client_id" uuid not null,
    "service_id" bigint not null,
    "client_organization_id" uuid not null
);


alter table "public"."client_services" enable row level security;

CREATE UNIQUE INDEX client_services_pkey ON public.client_services USING btree (id);

alter table "public"."client_services" add constraint "client_services_pkey" PRIMARY KEY using index "client_services_pkey";

alter table "public"."client_services" add constraint "client_services_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;

alter table "public"."client_services" validate constraint "client_services_client_id_fkey";

alter table "public"."client_services" add constraint "client_services_client_organization_id_fkey" FOREIGN KEY (client_organization_id) REFERENCES accounts(id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;

alter table "public"."client_services" validate constraint "client_services_client_organization_id_fkey";

alter table "public"."client_services" add constraint "client_services_created_by_fkey" FOREIGN KEY (created_by) REFERENCES accounts(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."client_services" validate constraint "client_services_created_by_fkey";

alter table "public"."client_services" add constraint "client_services_service_id_fkey" FOREIGN KEY (service_id) REFERENCES services(id) ON UPDATE CASCADE ON DELETE SET DEFAULT not valid;

alter table "public"."client_services" validate constraint "client_services_service_id_fkey";

grant delete on table "public"."client_services" to "anon";

grant insert on table "public"."client_services" to "anon";

grant references on table "public"."client_services" to "anon";

grant select on table "public"."client_services" to "anon";

grant trigger on table "public"."client_services" to "anon";

grant truncate on table "public"."client_services" to "anon";

grant update on table "public"."client_services" to "anon";

grant delete on table "public"."client_services" to "authenticated";

grant insert on table "public"."client_services" to "authenticated";

grant references on table "public"."client_services" to "authenticated";

grant select on table "public"."client_services" to "authenticated";

grant trigger on table "public"."client_services" to "authenticated";

grant truncate on table "public"."client_services" to "authenticated";

grant update on table "public"."client_services" to "authenticated";

grant delete on table "public"."client_services" to "service_role";

grant insert on table "public"."client_services" to "service_role";

grant references on table "public"."client_services" to "service_role";

grant select on table "public"."client_services" to "service_role";

grant trigger on table "public"."client_services" to "service_role";

grant truncate on table "public"."client_services" to "service_role";

grant update on table "public"."client_services" to "service_role";

create policy "Allow create to authenticated"
on "public"."client_services"
as permissive
for insert
to authenticated
with check (true);


create policy "Allow delete to authenticated"
on "public"."client_services"
as permissive
for delete
to authenticated
using (true);


create policy "Allow read to authenticated users"
on "public"."client_services"
as permissive
for select
to authenticated
using (true);


create policy "Allow update to authenticated"
on "public"."client_services"
as permissive
for update
to authenticated
using (true);
