create table "public"."services" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "price" double precision,
    "number_of_clients" bigint default '0'::bigint,
    "status" text default 'Active'::text,
    "propietary_organization_id" text
);


alter table "public"."services" enable row level security;

CREATE UNIQUE INDEX services_pkey ON public.services USING btree (id);

alter table "public"."services" add constraint "services_pkey" PRIMARY KEY using index "services_pkey";

grant delete on table "public"."services" to "anon";

grant insert on table "public"."services" to "anon";

grant references on table "public"."services" to "anon";

grant select on table "public"."services" to "anon";

grant trigger on table "public"."services" to "anon";

grant truncate on table "public"."services" to "anon";

grant update on table "public"."services" to "anon";

grant delete on table "public"."services" to "authenticated";

grant insert on table "public"."services" to "authenticated";

grant references on table "public"."services" to "authenticated";

grant select on table "public"."services" to "authenticated";

grant trigger on table "public"."services" to "authenticated";

grant truncate on table "public"."services" to "authenticated";

grant update on table "public"."services" to "authenticated";

grant delete on table "public"."services" to "service_role";

grant insert on table "public"."services" to "service_role";

grant references on table "public"."services" to "service_role";

grant select on table "public"."services" to "service_role";

grant trigger on table "public"."services" to "service_role";

grant truncate on table "public"."services" to "service_role";

grant update on table "public"."services" to "service_role";

create policy "create_service"
on "public"."services"
as permissive
for insert
to authenticated
with check (true);


create policy "delete_service"
on "public"."services"
as permissive
for delete
to authenticated
using (true);


create policy "read_service"
on "public"."services"
as permissive
for select
to authenticated
using (true);


create policy "update_service"
on "public"."services"
as permissive
for update
to authenticated
using (true);



