create type "public"."embed_location" as enum ('tab', 'sidebar');

create type "public"."embed_types" as enum ('url', 'iframe');

create table "public"."embed_accounts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "embed_id" uuid not null,
    "account_id" uuid not null
);

alter table "public"."embed_accounts" enable row level security;

create table "public"."embeds" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "deleted_on" timestamp with time zone,
    "title" text,
    "value" text not null,
    "icon" text,
    "location" embed_location not null default 'tab'::embed_location,
    "user_id" uuid not null,
    "organization_id" uuid not null,
    "visibility" visibility default 'public'::visibility,
    "type" embed_types not null default 'url'::embed_types
);

alter table "public"."embeds" enable row level security;

CREATE UNIQUE INDEX embed_accounts_pkey ON public.embed_accounts USING btree (id);

CREATE UNIQUE INDEX embeds_pkey ON public.embeds USING btree (id);

alter table "public"."embed_accounts" add constraint "embed_accounts_pkey" PRIMARY KEY using index "embed_accounts_pkey";

alter table "public"."embeds" add constraint "embeds_pkey" PRIMARY KEY using index "embeds_pkey";

alter table "public"."embed_accounts" add constraint "embed_accounts_account_id_fkey" FOREIGN KEY (account_id) REFERENCES accounts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."embed_accounts" validate constraint "embed_accounts_account_id_fkey";

alter table "public"."embed_accounts" add constraint "embed_accounts_embed_id_fkey" FOREIGN KEY (embed_id) REFERENCES embeds(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."embed_accounts" validate constraint "embed_accounts_embed_id_fkey";

alter table "public"."embeds" add constraint "embeds_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES accounts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."embeds" validate constraint "embeds_organization_id_fkey";

alter table "public"."embeds" add constraint "embeds_user_id_fkey" FOREIGN KEY (user_id) REFERENCES accounts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."embeds" validate constraint "embeds_user_id_fkey";

grant delete on table "public"."embed_accounts" to "anon";

grant insert on table "public"."embed_accounts" to "anon";

grant references on table "public"."embed_accounts" to "anon";

grant select on table "public"."embed_accounts" to "anon";

grant trigger on table "public"."embed_accounts" to "anon";

grant truncate on table "public"."embed_accounts" to "anon";

grant update on table "public"."embed_accounts" to "anon";

grant delete on table "public"."embed_accounts" to "authenticated";

grant insert on table "public"."embed_accounts" to "authenticated";

grant references on table "public"."embed_accounts" to "authenticated";

grant select on table "public"."embed_accounts" to "authenticated";

grant trigger on table "public"."embed_accounts" to "authenticated";

grant truncate on table "public"."embed_accounts" to "authenticated";

grant update on table "public"."embed_accounts" to "authenticated";

grant delete on table "public"."embed_accounts" to "service_role";

grant insert on table "public"."embed_accounts" to "service_role";

grant references on table "public"."embed_accounts" to "service_role";

grant select on table "public"."embed_accounts" to "service_role";

grant trigger on table "public"."embed_accounts" to "service_role";

grant truncate on table "public"."embed_accounts" to "service_role";

grant update on table "public"."embed_accounts" to "service_role";

grant delete on table "public"."embeds" to "anon";

grant insert on table "public"."embeds" to "anon";

grant references on table "public"."embeds" to "anon";

grant select on table "public"."embeds" to "anon";

grant trigger on table "public"."embeds" to "anon";

grant truncate on table "public"."embeds" to "anon";

grant update on table "public"."embeds" to "anon";

grant delete on table "public"."embeds" to "authenticated";

grant insert on table "public"."embeds" to "authenticated";

grant references on table "public"."embeds" to "authenticated";

grant select on table "public"."embeds" to "authenticated";

grant trigger on table "public"."embeds" to "authenticated";

grant truncate on table "public"."embeds" to "authenticated";

grant update on table "public"."embeds" to "authenticated";

grant delete on table "public"."embeds" to "service_role";

grant insert on table "public"."embeds" to "service_role";

grant references on table "public"."embeds" to "service_role";

grant select on table "public"."embeds" to "service_role";

grant trigger on table "public"."embeds" to "service_role";

grant truncate on table "public"."embeds" to "service_role";

grant update on table "public"."embeds" to "service_role";