"use client";

import React from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

import { Button } from "@kit/ui/button";
import { Form } from "@kit/ui/form";
import { invoiceSchema, InvoiceFormData } from "../../../schemas/schema";
import { InvoiceInformationSection } from "../../../components/form/information-section";
import { InvoiceItemsSection } from "../../../components/form/items-section";
import { InvoiceNotesSection } from "../../../components/form/notes-section";
import { Trans } from "@kit/ui/trans";
import { Service } from "~/lib/services.types";
import { Client } from "~/lib/client.types";
import { createInvoice } from "~/server/actions/invoices/invoices.action";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { useRouter } from "next/navigation";
import { useTranslation } from "react-i18next";
import { Spinner } from "@kit/ui/spinner";

interface InvoiceFormProps {
  clients: Client.Response[];
  services: Service.Relationships.Billing.BillingService[];
  agencyId: string;
}

export function InvoiceForm({ clients, services, agencyId }: InvoiceFormProps) {
  const queryClient = useQueryClient();
  const router = useRouter();
  const { t } = useTranslation("invoices");
  const [isDraft, setIsDraft] = React.useState(false);

  const form = useForm<InvoiceFormData>({
    resolver: zodResolver(invoiceSchema),
    defaultValues: {
      clientId: "",
      dateOfIssue: new Date(),
      paymentMethod: "",
      paymentReference: "",
      lineItems: [{ description: "", rate: 0, quantity: 1, serviceId: 0 }],
      notes: "",
    },
    mode: "onBlur",
  });

  const invoiceMutation = useMutation({
    mutationFn: createInvoice,
    onSuccess: () => {
      toast.success(t("success.invoiceCreated"));
      void queryClient.invalidateQueries({ queryKey: ["invoices"] });
      router.push("/invoices");
    },
    onError: () => {
      toast.error(t("errors.failedToCreateInvoice"));
    },
  });

  const draftMutation = useMutation({
    mutationFn: createInvoice,
    onSuccess: () => {
      toast.success(t("success.invoiceDraftCreated"));
      void queryClient.invalidateQueries({ queryKey: ["invoices"] });
    },
    onError: () => {
      toast.error(t("errors.failedToCreateInvoice"));
    },
  });

  const onSubmit = async (data: InvoiceFormData) => {
    // Calculate totals
    const subtotal = data.lineItems.reduce(
      (sum, item) => sum + item.rate * item.quantity,
      0,
    );
    const totalAmount = subtotal; // Add tax logic here if needed

    // Calculate due date (30 days from issue date)
    const dueDate = new Date(data.dateOfIssue);
    dueDate.setDate(dueDate.getDate() + 30);

    // Handle form submission
    const invoice = {
      agency_id: agencyId,
      client_organization_id: data.clientId,
      number: "", // Auto-generated by trigger
      issue_date: data.dateOfIssue.toISOString()?.split("T")[0] ?? "",
      due_date: dueDate.toISOString()?.split("T")[0] ?? "",
      subtotal_amount: subtotal,
      total_amount: totalAmount,
      notes: data.notes ?? null,
      status: isDraft ? ("draft" as const) : ("issued" as const),
      invoice_items: data.lineItems.map((item) => ({
        invoice_id: "", // Will be set by the service
        description: item.description,
        service_id: item.serviceId,
        unit_price: item.rate,
        quantity: item.quantity,
        total_price: item.rate * item.quantity,
      })),
    };

    if (isDraft) {
      await draftMutation.mutateAsync(invoice);
    } else {
      await invoiceMutation.mutateAsync(invoice);
    }

    // Reset draft state after submission
    setIsDraft(false);
  };

  return (
    <Form {...form}>
      <form
        onSubmit={form.handleSubmit(onSubmit)}
        className="py-1 relative h-full flex flex-col"
      >
        <div className="flex-1 space-y-2">
          <InvoiceInformationSection control={form.control} clients={clients} />

          <InvoiceItemsSection
            control={form.control}
            setValue={form.setValue}
            services={services}
          />

          <InvoiceNotesSection control={form.control} />
        </div>

        {/* Action Buttons */}
        <div className="flex justify-end gap-3 pt-4 sticky bottom-0 w-full py-8 bg-white">
          <Button
            type="submit"
            variant="outline"
            onClick={() => setIsDraft(true)}
            className="flex items-center gap-2"
          >
            <Trans i18nKey="invoices:creation.form.actions.saveAsDraft" />
            {draftMutation.isPending ? <Spinner className="w-4 h-4" /> : null}
          </Button>
          <Button
            type="submit"
            onClick={() => setIsDraft(false)}
            className="flex items-center gap-2"
          >
            <Trans i18nKey="invoices:creation.form.actions.createInvoice" />
            {invoiceMutation.isPending ? <Spinner className="w-4 h-4" /> : null}
          </Button>
        </div>
      </form>
    </Form>
  );
}
